### ISSUE TITLE
messagePayload.fromId should always be set.

### ISSUE THREAD

**Issue by huan** [wechaty/puppet-padlocal#100]
See:

- https://github.com/wechaty/wechaty/issues/2252

The message payload from padlocal sometimes has no `fromId` value which should not.

**Comment by huan** [comment]
This bug will block all operations when we need to call `message.talker()` on the message which has no `payload.fromId` set.

This blocked the Friday BOT duplicated message checking algorithm:

https://github.com/wechaty/friday/blob/8d461312276d5e7756083e4b4564ade081cb4c81/src/core/sync-community-rooms/events/handlers/puppet-message-received.handler.ts#L99-L104

And it seems that the `UrlLink` message is missing the `payload.fromId`.

**Comment by padlocal** [comment]
This problem is we need to extract actual `talkerId` from message payload for room messages that sent by others. And it works for most room messages currently: https://github.com/wechaty/puppet-padlocal/blob/0e8456cd660f772c730e9268ee853d61730b703b/src/padlocal/schema-mapper/index.ts#L59

But for some specialy messages (e.g. 10002), we need to do this case by case. I don't have enough samples to process unfortunately.

I can fill `talkerId` with `roomId` as a temporary workaround.

So if you meet this issue, please proviod detailed message payload, this will help us to resolve your cases.

**Comment by huan** [comment]
> I can fill talkerId with roomId as a temporary workaround.

Please don't do that. A `talkerId` must be a contact id, it must not be a `roomId`, or will cause Wechaty internal exceptions: it can never get payload as a contact id.

> So if you meet this issue, please proviod detailed message payload, this will help us to resolve your cases.

No problem, I'll post more details when I met this issue in the future.

**Comment by padlocal** [comment]
OK, let's make this issue stay open, as long as we figure out enough cases.

**Comment by padlocal** [comment]
We have fixed this issue by supporting `talkerId` for various messages . And released in wechaty-puppet-padlocal@1.11.19
